import { Pool } from "pg";
import "dotenv/config"

console.log("Connecting to the database...")
export const client = new Pool({
    host : process.env.PGHOST,
    password : process.env.PGPASSWORD,
    database : process.env.PGDATABASE,
    user : process.env.PGUSER,
    port : process.env.PGHOSTPORT,
})


await client.query(
    `
    CREATE TABLE IF NOT EXISTS users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255) NOT NULL UNIQUE,
    password_hash text NOT NULL,
    created_at timestamp without time zone DEFAULT now()
    );
    `
)
